swagger: "2.0"
info:
  description: "This is a simple API to display smiley pictures on a screen of a Raspberry PI running a Flogo IoT application"
  version: "1.0.0"
  title: "Flogo Smiley Demo"
  contact:
    email: "flogo@sqits.net"
  license:
    name: "BSD-3-Clause"
    url: "https://opensource.org/licenses/BSD-3-Clause"
host: "smiley.square-it.grp"
basePath: "/v1"
tags:
- name: "smiley"
  description: "Operations about smileys"
schemes:
- "http"
paths:
  /smiley/{smileyId}:
    get:
      tags:
      - "smiley"
      summary: "Display a smiley by ID"
      description: "Triggers the display of the selected smiley on the Raspberry screen"
      operationId: "displaySmileyById"
      produces:
      - "application/json"
      parameters:
      - name: "smileyId"
        in: "path"
        description: "ID of smiley to display or string representation of smiley like :some_smiley:"
        required: true
        type: "string"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SmileyResponse"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Smiley not found"
definitions:
  Smiley:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      alternateDisplay:
        type: "string"
        description: "An ASCII-based representation of the smiley"
  SmileyResponse:
    type: "object"
    properties:
      displayed:
        type: "boolean"
externalDocs:
  description: "Find out more about the Flogo Smiley Demo"
  url: "https://github.com/square-it"
